steps:
    - name: node:18
      entrypoint: yarn
      args:
      - install
    - name: node:18
      entrypoint: yarn
      args:
      - build
    - name: "gcr.io/cloud-builders/gcloud"
      args: ["app", "deploy"]
      entrypoint: bash
options:
    logging: CLOUD_LOGGING_ONLY